/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

//const awsmobile = {
//    "aws_project_region": "ap-southeast-2"
//};


//export default awsmobile;
import { environment } from './environments/environment.ts';

const awsconfig = {
  region: environment.region,
  // OPTIONAL - Amazon Cognito User Pool ID
  userPoolId: environment.userPoolId,
  // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
  userPoolWebClientId: environment.userPoolWebClientId,
  authenticationFlowType: 'USER_PASSWORD_AUTH',

  //DEV Pool
  // // REQUIRED - Amazon Cognito Region
  //region: 'ap-southeast-2',
  //// OPTIONAL - Amazon Cognito User Pool ID
  //userPoolId: 'ap-southeast-2_nfHuSVZSa',
  //// OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
  //userPoolWebClientId: '4d99r5si253niabl6qcgcq1lr1',
  //// OPTIONAL - Manually set the authentication flow type. Default is 'USER_SRP_AUTH'
  //authenticationFlowType: 'USER_PASSWORD_AUTH',

  /***TEST pool
   *
   */
  // REQUIRED - Amazon Cognito Region
  //region: 'ap-southeast-2',
  // OPTIONAL - Amazon Cognito User Pool ID
  //userPoolId: 'ap-southeast-2_OMQPUGGcl',
  // OPTIONAL - Amazon Cognito Web Client ID (26-char alphanumeric string)
  //userPoolWebClientId:  '2m801p27jmhrcrn8v2oi1q0stc',
  // OPTIONAL - Manually set the authentication flow type. Default is 'USER_SRP_AUTH'
  //authenticationFlowType: 'USER_PASSWORD_AUTH',
 
  
  // OPTIONAL - Hosted UI configuration
  //oauth: {
  //  domain: 'your_cognito_domain',
  //    scope: ['phone', 'email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
  //      redirectSignIn: 'http://localhost:3000/',
  //        redirectSignOut: 'http://localhost:3000/',
  //          responseType: 'code' // or 'token', note that REFRESH token will only be generated when the responseType is code
  //}
}

export default awsconfig;
